name: Sync Leetcode

on:
  workflow_dispatch:      # Allows you to run the sync manually
  schedule:
    - cron: "0 23 * * *"    # Runs automatically every Saturday at 8:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions  # Folder where your code will be stored
          verbose: true
